### ISSUE TITLE
 Tanuki.Projects.Repository.Files.find puts params into the body.

### ISSUE THREAD

**Issue by Fahrradflucht** [ZJvandeWeg/Tanuki#1]
I'm not sure where development is should happen for this project (Gitlab or Github).

https://gitlab.com/zj/Tanuki/issues/1 is where a laid out the problem anyway.

**Comment by ZJvandeWeg** [comment]
I've reviewed [your MR](https://gitlab.com/zj/Tanuki/merge_requests/2) over at GL. As you opened an issue there too, Ill close this one.
